robot_main_state_node:
  ros__parameters:
    waypoints_start_to_challenge_zone: 
      start: [0.0, 0.0, 0.0]
      sub: [1.75, 0.0, 0.0]
      challenge_zone: [1.75, 0.48, -150.0]

    lists_challenge_zone: 
      room1: [-0.19, 0.67, -180.0]
      room2: [0.335, 0.67, -180.0]
      room3: [0.79, 0.67, -180.0]
      room4: [1.26, 0.67, -180.0]
      room5: [1.786, 0.67, -180.0]