robot_main_state_node:
  ros__parameters:
    waypoints_start_to_challenge_zone: 
      start: [0.0, 0.0, 0.0]
      sub: [1.8, 0.0, 0.0]
      challenge_zone: [1.8, 0.5, 0.0]

    lists_challenge_zone: 
      room1: [-0.126, 0.65, -90.0]
      room2: [0.31, 0.65, -90.0]
      room3: [0.76, 0.65, -90.0]
      room4: [1.185, 0.65, -90.0]
      room5: [1.8, 0.65, -90.0]